import 'package:codera/Cards/coursecard.dart';
import 'package:flutter/material.dart';

class AllCourses extends StatefulWidget {
  @override
  _AllCoursesState createState() => _AllCoursesState();
}

class _AllCoursesState extends State<AllCourses> {
  @override
  Widget build(BuildContext context) {
    MediaQueryData queryData;
    queryData = MediaQuery.of(context);
    var screenHeight = queryData.size.height;
    var screenWidth = queryData.size.width;
    return 
    Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: <Widget>[
        Row(
          mainAxisAlignment: MainAxisAlignment.start,
          children: <Widget>[
            SizedBox(width: screenWidth * 0.13),
            Text(
              'All Courses',
              style: TextStyle(fontSize: 16.0, fontWeight: FontWeight.bold),
            ),
          ],
        ),
        SizedBox(height: screenHeight * 0.045),
        Wrap(
          direction: Axis.horizontal,
          spacing: 20.0,
          runSpacing: 20.0,
          children: <Widget>[
              CourseCard(
                cardimage: 'https://drive.google.com/uc?export=view&id=15z-IcKtErPYCRwy9IHIFPXTVsP6lmW9x',
                courseimage: 'https://drive.google.com/uc?export=view&id=1HwTCLWElzxRB6C0lPL4VW-tnPGm-j_67',
                courselink: 'https://drive.google.com/drive/folders/0B0DQiknXaFG3bkdNUG8wYkFIZjA?usp=sharing',
                buttoncolor: '0xFF00e8ff',
                buttontextcolor: '0xFF0e37f1',
                accentcolor: '0xFFfe19aa',
                title: 'AI Fundamentals',
                overview: 'Artificial Intelligence (AI) is a field that has a long history but is still constantly and actively growing and changing. In this course, you’ll learn the basics of modern AI as well as some of the representative applications of AI. Along the way, we also hope to excite you about the numerous applications and huge possibilities in the field of AI, which continues to expand human capability beyond our imagination.',
                objective: '~ Statistics, Uncertainty, and Bayes networks.\n~ Machine learning.\n~ Logic and planning.\n~ Image processing and computer vision.\n~ Robotics and robot motion planning.\n~ Natural language processing and information retrieval.',
                source: 'Udemy',
                popularity: 70.4,
                height: 0.55,
                width: 0.848,
              ),
              CourseCard(
                cardimage: 'https://drive.google.com/uc?export=view&id=1z5eTNZJQ-MWq-hhGLJbMqFhY5ngqHPYD',
                courseimage: 'https://drive.google.com/uc?export=view&id=1Tt9_eeJ8oIsJ_90p2hFGq0Zjyv5jqMwY',
                courselink: 'https://drive.google.com/open?id=0ByWO0aO1eI_MUzJkLVFSR0pTUHM',
                buttoncolor: 0xFF00FFBA,
                buttontextcolor: 0xffF81D92,
                accentcolor: 0xff9B46C0,
                title: 'Front End Web Development',
                overview: 'This course covers the most popular web development frameworks, and will get you started on your path towards becoming a full-stack web developer!\n\nIf you would like to get started as a front-end web developer, you are going to LOVE this course! Work on projects ranging from a simple HTML page to a complete JavaScript based Google Chrome extension. We will cover the following technologies in this course:\n\n~ Web development basics with HTML\n~ Cascading Style Sheets (CSS)\n~ JavaScript programming\n~ jQuery JavaScript library\n~ Bootstrap framework',
                objective: '~ Build a simple HTML text site\n~ Program websites with JavaScript\n~ Build and publish a Google Chrome Extension\n~ Style web pages using CSS & SASS\n~ Build complete Web Project',
                source: 'Team TreeHouse',
                popularity: 76.66,
                height: 0.4,
                width: 0.4,
              ),
              CourseCard(
                cardimage: 'https://drive.google.com/uc?export=view&id=1XNOpSpxAsfK5whbF2DK3ar1cl-NJ_m-G',
                courseimage: 'https://drive.google.com/uc?export=view&id=1czekExpmgGsthOAARMmC04uSWf0aFKOp',
                courselink: 'https://drive.google.com/open?id=1GVgXNFnbolos08y1a2niRQ_Add1itCsE',
                buttoncolor: 0xFF8C52FF,
                buttontextcolor: 0xffFFDE59,
                accentcolor: 0xffDD88F9,
                title: 'Kotlin for Android Development',
                overview: 'This course is all about devloping android apps with the use of Kotlin language, which is announced as official language by google for android development. Learn to architect and develop Android apps in the Kotlin programming language using industry-proven tools and libraries. With these techniques you\'ll create apps in less time, writing less code, and with fewer errors. This course demonstrates how to take a basic Android app in Java and convert it to Kotlin, teaching you key features of the Kotlin programming language along the way. This is an efficient, fast-paced introduction to Kotlin for experienced Java programmers.',
                objective: '~ Explore the basics of Android, such as creating text, images, and interactive buttons\n~ Set up the development environment and create a Dice Roller Android app\n~ Navigate the Main Map Anatomy of an Android app\n~ Learn different kinds of views and resources\n~ Explore arranging elements with the Android Studio\'s Layout Editor\n~ Connect views with data through data binding\n~ Learn how to build apps that contain multiple screens known as destinations\n~ Debug common issues through an understanding of lifecycles\n~ Learn one way to structure an Android app and the benefits that come with this design',
                source: 'Udemy',
                popularity: 72.4,
                height: 0.4,
                width: 0.4,
              ),
              CourseCard(
                cardimage: 'https://drive.google.com/uc?export=view&id=1Of8xZQ-Yj1nsv6gM8RGdfRVbvxsy_G_Q',
                courseimage: 'https://drive.google.com/uc?export=view&id=1xkIh5GUG3OH3yjxqVMzGxPMlScvFhB8a',
                courselink: 'https://drive.google.com/open?id=1enAyu5mN4ykS-67oC5vkDBbiyeQHuS_t',
                buttoncolor: 0xFF000000,
                buttontextcolor: 0xFFff61f4,
                accentcolor: 0xFFff9100,
                title: 'Complete Ethical Hacking',
                overview: 'Gain the ability to do ethical hacking and penetration testing by taking this course! Get answers from an experienced IT expert to every single question you have related to the learning you do in this course including installing Kali Linux, using VirtualBox, basics of Linux, Tor, Proxychains, VPN, Macchanger, Nmap, cracking wifi, aircrack, DoS attacks, SLL strip, known vulnerabilities, SQL injections, cracking Linux passwords.',
                objective: '~ Answers to every single question you have about ethical hacking and penetration testing from an experienced IT professional!\n~ A guide to using these skills to get a better job and make money online as a freelancer.\n~ A complete tutorial explaining how to build a virtual hacking environment, attack networks, and break passwords.\n~ Tips for remaining anonymous in hacking and penetration testing activities.\n~ The ability to secure and protect any network from hackers and loss of data.\n~ Step by step instructions for insulation VirtualBox and creating your virtual environment on Windows, Mac, and Linux.',
                source: 'Udemy',
                popularity: 79.8,
                height: 0.4,
                width: 0.4,
              ),
                       CourseCard(
                              accentcolor: 0xff000949,
                              buttoncolor: 0xffff7824,
                              buttontextcolor: 0xff000949,
                              cardimage: 'https://drive.google.com/uc?export=view&id=1hwtznRaCc65uuXCcb6pYyM74DT29WAB_',
                              courseimage: 'https://drive.google.com/uc?export=view&id=1202kV4aLM14Mfu180Bqv-84c65B2mOMx',
                              courselink: 'https://drive.google.com/open?id=0B1HQDi7EkA9XUlBZQThMYU5pSUk',
                              width: 0.4,
                              height: 0.4,
                              objective: '~ How to get started with app development and create your very first iOS app\n~ How to utilise the Apple developer tools (Xcode, Instruments, debugger, analyzer, and iOS Simulator) to build your app\n~ How to implement a range of features using the Swift programming language\n~ How to distinguish well-written code from poorly-written code and follow programming best practices in Swift\n~ The process and steps required to get your app on the App Store',
                              overview: 'In this Professional program you will learn the tools, techniques and concepts needed to build a basic iOS app, from scratch.\nFind out how to program in Swift and utilise the iOS Software Development Kit (SDK) and Apple developer tools (Xcode, debugger, analyzer and iOS Simulator) to create mobile apps which can be sold via the App Store.\n\nIn each course you will work through a range of lessons and projects which will focus on Swift programming and teach you about various aspects of app development. These lessons will provide you with the practical, hands-on skills needed to embark on a career in app development\n\nIn addition, a number of app development companies will share their experiences in building and developing apps so you can find out what it really takes to turn your brilliant idea into a functioning product.',
                              popularity: 48.6,
                              source: 'Udemy',
                              title: 'App Development with Swift',
                            ),
                        CourseCard(
                          accentcolor: 0xFF7a0cf0,
                          buttoncolor: 0xFFeb0e87,
                          buttontextcolor: 0xffeaff00,
                          cardimage: 'https://drive.google.com/uc?export=view&id=1ruYuBkyPLdlyGQZI32TdVnCdipyJfSc-',
                          courseimage: 'https://drive.google.com/uc?export=view&id=1MmUJJqYNE3AQLSAzLqqyK1zP1Zuy0Mh7',
                          courselink: 'https://drive.google.com/open?id=0ByWO0aO1eI_MdkZwY2VRNzEtbDg',
                          objective: '~ Understand the basic syntax and control structures of the language\n~ Apply Go’s concurrency model to build massively parallel systems\n~ Grasp the purpose of types, which is especially important if you’re coming from a dynamically typed language like Javascript or Ruby\n~ Organize code through the use of packages\n~ Use the Go runtime to build and compile projects\n~ Get insight into critical design decisions in the language\n~ Gain a sense of when to use basic language features',
                          overview: 'This course is designed to get you up and running as fast as possible with Go. We\’ll quickly cover the basics, then dive into some of the more advanced features of the language.\nGo is designed to be easy to pick up, but tough to master. Through multiple projects, quizzes, and assignments, you\’ll quickly start to master the language\’s quirks and oddities. Go is like any other language — you have to write code to learn it! This course will give you ample opportunities to strike out on your own and start working on your own programs.',
                          source: 'Udemy',
                          title: 'Let\'s GO',
                          popularity: 66.0,
                          height: 0.4,
                          width: 0.4,
                        ),
              CourseCard(
                cardimage: 'https://drive.google.com/uc?export=view&id=1L_2lQTm_sq_Y6JJgjI1WtJIxhEMDw-SL',
                courseimage: 'https://drive.google.com/uc?export=view&id=1V_Cdq1rJ4cxUO2nWuZk_B_LqLjcOlR-4',
                courselink: 'https://drive.google.com/open?id=0ByWO0aO1eI_MbExXU3JXZWNZZGM',
                buttoncolor: 0xFFFDD755,
                buttontextcolor: 0xff255EFD,
                accentcolor: 0xffFA836D,
                title: 'Complete PHP',
                overview: 'One of the most powerful server-scripting languages requires an equally powerful course to help break down the tricky concepts of Object Oriented PHP in a step by step manner to help you master OOP PHP.\nThis course was designed to simplify the process of understanding OOP PHP in the easiest and most accurate manner. The OOP PHP tutorial breaks down the basics of PHP coding, how it works with OOP and even how to combine both to effectively create a website.\nThe course starts by covering simple concepts such as classes, objects, methods, properties, MVC, MySQL, Data Abstraction, Data Binding, etc. Following the fundamentals, you’ll then progress on to more advanced topics before you can use everything you’ve learned to create a functional website with OOP PHP.\nHere’s a course that simplifies your life and teaches you one of the greatest paradigm changes made to the powerful PHP language. So, enroll now and see how OOP PHP can change your life.',
                objective: '~ Build a complete website using classes and objects in PHP\n~ Learn all about Abstraction and Inheritance\n~ Understand the concepts behind object oriented PHP\n~ Learn how to deal with RDBMS within OOPS framework',
                source: 'Udemy',
                popularity: 60.4,
                height: 0.4,
                width: 0.4,
              ),
                        CourseCard(
                          accentcolor: 0xFF0f67f5,
                          buttoncolor: 0xFF36a1ff,
                          buttontextcolor: 0xff000000,
                          cardimage: 'https://drive.google.com/uc?export=view&id=1-o-insCoGXLW8_FDKBlBYhpJ8kegiShx',
                          courseimage: 'https://drive.google.com/uc?export=view&id=1B5pHIDsQ5l6mO8zuC_8-aM5x7Hvaj-Bw',
                          courselink: 'https://drive.google.com/open?id=13uL1tQwHoRxiKDejOadR3mMVCHxx3PwJ',
                          objective: '~ Understand the fundamentals of the Flutter framework\n~ Incorporate widgets and state into your app\n~ Use Flutter\'s tools to enhance your development process\n~ Customize your app with Material Design, themes, assets, and more\n~ Make your app interactive with text input, gestures, and more\n~ Retrieve local and real-time data from the web\n~ Build your own Real world Application\n~ Other Apps examples & Features',
                          overview: 'In this course, you\'ll learn how to use Flutter to quickly develop high-quality, interactive mobile applications for iOS and Android devices. Whether you\’re just getting started with mobile app development, or experienced with other mobile app frameworks, you\’ll enjoy the high-velocity development and quality apps that Flutter enables. Learn how to develop fast by making use of Flutter\'s reactive framework, stateful Hot Reload, and integrated tooling. Customize your app with rich, composable widgets, built-in animations, and a layered, extensible architecture.\n\nAfter completing this course you would be able to make any app for Android, iOS, Website and Desktop(Beta).',
                          source: 'Udemy',
                          title: 'Complete Flutter App Development',
                          popularity: 56.0,
                          height: 0.4,
                          width: 0.4,
                        ),
              CourseCard(
                cardimage: 'https://drive.google.com/uc?export=view&id=1gE3q4MOX9MsDclfSrc9tMfG88Ate35pC',
                courseimage: 'https://drive.google.com/uc?export=view&id=15FMZ35yCBiIxg9ilvhqeaYV66sQOwjMT',
                courselink: 'https://drive.google.com/open?id=0B1HQDi7EkA9XVWtHZGE5U1FZb0U',
                buttoncolor: 0xFF000000,
                buttontextcolor: 0xFFffda05,
                accentcolor: 0xFFff9100,
                title: 'Hacking for Beginners',
                overview: 'This is how this course will guide to into your first hack in two hours!\nYou want to learn hacking but you don\'t know where to start? Then this is the course for you. Hacking for beginners course requires zero experience, zero programming knowledge and zero Linux knowledge.\nWe start with the assumption that you know nothing about hacking, networks or the web. And step by step we will build up your knowledge so you can perform you first hack in two hours.',
                objective: '~ Understand the internet and the components that make it work\n~ What are IP addresses and why they\'re needed for hacking\n~ What is a DNS and how it makes the internet work\n~ What are servers and services and why are needed for hacking\n~ Deep dive into packets\n~ Set up your own lab to practice hacking legally\n~ Get introduced to port scanning and one of the favorite tools for hackers\n~ Understand vulnerability scanning and how you can identify weaknesses\n~ Exploit the weaknesses you find to hack your target.',
                source: 'Udemy',
                popularity: 64.4,
                height: 0.4,
                width: 0.4,
              ),
              CourseCard(
                cardimage: 'https://drive.google.com/uc?export=view&id=1Ooa2dwgD-jj9HBB3B9kXetvahspvR16X',
                courseimage: 'https://drive.google.com/uc?export=view&id=1UMiBNY0deyDgP_luoPmbG_HtxYXx0zdD',
                courselink: 'https://drive.google.com/open?id=0B1HQDi7EkA9XTTdhRzh0cDRYWEk',
                buttoncolor: 0xFFFFDE59,
                buttontextcolor: 0xffB68FE5,
                accentcolor: 0xff40B4F9,
                title: 'Mordern JavaScript Course',
                overview: 'Have you ever wanted to learn how to code but didn\'t know where to start? This is a fantastic course to start. Not only is JavaScript easy to learn but it is in demand? If you take this course you will start the fantastic process of learning to code which will lead you to a better life. Coding is one of the most in demand skills if you can code you have a job.',
                objective: '~ Learn the basics of JavaScript\n~ Learn the basics of programming\n~ Build modern and functional websites\n~ Build real world website',
                source: 'Udemy',
                popularity: 60.4,
                height: 0.4,
                width: 0.4,
              ),
              CourseCard(
                cardimage: 'https://drive.google.com/uc?export=view&id=1ws6IscNwlSPQ1mq4NeP53tmus6XebuTL',
                courseimage: 'https://drive.google.com/uc?export=view&id=14Z6pPPXtxunDw2OjvCRbimluNrHo41vA',
                courselink: 'https://drive.google.com/open?id=0ByWO0aO1eI_MamwydHF5MGg2WFE',
                buttoncolor: 0xFF349FF6,
                buttontextcolor: 0xFFA6E8DE,
                accentcolor: 0xFFF9428F,
                title: 'Ultimate C',
                overview: 'In this ultimate C course, you will build command over c language. This is a complete overview course which builds your foundation of C language. In this course you will understand variables and the different data types, be able to utilize functions and arrays, understand the  concept of pointers, learn about control flow (decision statements and iteration).\nYou will be in a position to apply for real-time programming positions, and truly understand the core language that most modern languages are based on!\nIf you have previously used the C programming language, then this course will deepen your understanding of it. If you have never used it, no problem, you will see that it can help you become a more efficient C developer.',
                objective: '~ Understand the fundamentals of the C Programming Language\n~ Create your first C Application\n~ Understand variables and the different data types\n~ Understand the core language that most modern languages are based on\n~ Make yourself more marketable for entry level programming positions\n~ Apply for real-time programming positions\n~ Learn how to write high-quality code',
                source: 'Lynda',
                popularity: 88.4,
                height: 0.4,
                width: 0.4,
              ),
              CourseCard(
                cardimage: 'https://drive.google.com/uc?export=view&id=1mGD52SmzEQpWe8umA_ueJq7EPIzEj6wp',
                courseimage: 'https://drive.google.com/uc?export=view&id=1Xtb1vXefZX3CdjW5rR5aocs9BjKRMnXk',
                courselink: 'https://drive.google.com/open?id=0B1HQDi7EkA9Xd2J3MXJxNDZkTWs',
                buttoncolor: 0xFFFF914D,
                buttontextcolor: 0xff000000,
                accentcolor: 0xffFF3E57,
                title: 'Java Basics',
                overview: 'Learn the basic concepts, tools, and functions that you will eventually use to build both desktop and mobile applications with the popular programming language, Java.\nThis course was designed to teach you the essential Java programming skills you need to get your first programming job, or perhaps a promotion to a more senior position.  And to do it in the shortest possible amount of time.',
                objective: '~ Understand the basic fundamentals of Java\n~ Create Java desktop or web apps\n~ Create Android apps with solid Java knowledge\n~ Build keen foundation of Java Programming language\n~ Build Real World applications using Java',
                source: 'Udemy',
                popularity: 52.4,
                height: 0.4,
                width: 0.4,
              ),
               CourseCard(
                          accentcolor: 0xFF008cbf,
                          buttoncolor: 0xFF36ff97,
                          buttontextcolor: 0xff095900,
                          cardimage: 'https://drive.google.com/uc?export=view&id=14d6ZmnF1h1ERrQoC0BqKWYi3-KlXBc7y',
                          courseimage: 'https://drive.google.com/uc?export=view&id=1P-LhbWu2XQwPYJlmiLUTWHIfoRPvVsI8',
                          courselink: 'https://drive.google.com/open?id=1bOCkovr7b8wN98Mo--gWMEQNEqIbHv_C',
                          objective: '~ Master the fundamentals of writing Python scripts\n~ Learn core Python scripting elements such as variables and flow control structures\n~ Discover how to work with lists and sequence data\n~ Write Python functions to facilitate code reuse\n~ Use Python to read and write files\n~ Make their code robust by handling errors and exceptions properly\n~ Work with the Python standard library\n~ Explore Python\'s object-oriented features\n~ Search text using regular expressions',
                          overview: 'The ultimate python bootcamp, training course leads the students from the basics of writing and running Python scripts to more advanced features such as file operations, regular expressions, working with binary data, and using the extensive functionality of Python 3 modules. Extra emphasis is placed on features unique to Python, such as tuples, array slices, and output formatting.',
                          source: 'Udemy',
                          title: 'Python 3 - The Ultimate Bootcamp',
                          popularity: 87.0,
                          height: 0.4,
                          width: 0.4,
                        ),
              CourseCard(
                cardimage: 'https://drive.google.com/uc?export=view&id=17ke06xtAliQK2o_l8O1-1yBWzShrHC_L',
                courseimage: 'https://drive.google.com/uc?export=view&id=1gmSdn4Qs-_6Qqko9RIKMZcJK76XTN_Ug',
                courselink: 'https://drive.google.com/open?id=0B1HQDi7EkA9XeHpLNlhWSkt2X2s',
                buttoncolor: 0xFF37004D,
                buttontextcolor: 0xffE1F82D,
                accentcolor: 0xff2CCFB3,
                title: 'Complete HTML',
                overview: 'HTML5 is one of the hot web technologies and is widely gaining acceptance across mobile and web. In our course you get a complete resource which can get you started on application development for HTML5. In our course you work on actual examples and go through important concepts required for through knowledge. In our course you will start with basic HTML tags. You will learn how to create HTML websites and use CSS in your work before we start discussing HTML5. We do not assume any prior knowledge so we go through the concepts from the beginner\'s point of view. In our HTML5 lectures we start with new tags and forms. We then gradually move to advance topics like Drag and Drop and Multimedia. We follow it with difficult topics like Geolocation, WebStorage and Application cache. This course creates easy to grasp examples for each of the concepts and by the end of it you will be able to understand the complete picture rather than just bits and pieces of the technology.',
                objective: '~ By the end of the course you will be able to create full fledged HTML5 websites\n~ You will have through understanding of both HTML and CSS\n~ You will be able to use features like Drag and Drop, Geo location and Web Storage to create immersible user experience.\n~ You will be able to create web applications for mobile phones as well',
                source: 'Udemy',
                popularity: 60.4,
                height: 0.4,
                width: 0.4,
              ),
              CourseCard(
                cardimage: 'https://drive.google.com/uc?export=view&id=1wD7rAwKPLTTtGN1yhdta81hn5o_d5kR8',
                courseimage: 'https://drive.google.com/uc?export=view&id=1A8aAgSJF1Q1VUUUGX91RnLW4Stvm94B4',
                courselink: 'https://drive.google.com/drive/folders/1Y71u46Cy9O6VKo-jeQnLiqN14VjQKkGv?usp=sharing',
                buttoncolor: 0xFFFFC822,
                buttontextcolor: 0xffF44594,
                accentcolor: 0xff9A80F9,
                title: 'Networking & Security',
                overview: 'There are a growing number of exciting, well-paying jobs in today’s security industry that do not require a traditional college degree. Forbes estimates that there will be as many as 3.5 million unfilled positions in the industry worldwide by 2021! One position with a severe shortage of skills is as a junior cybersecurity analyst. This specialization will provide you with the basics you need to get started. Throughout this specialization, you will learn concepts around cybersecurity tools and processes, system administration, operating system and database vulnerabilities, types of cyber attacks and basics of networking. You will also gain knowledge around important topics such as cryptography and digital forensics. This specialization is truly an international offering from IBM with experts from the United States, Costa Rica, Canada and Italy. These instructors are architects, Security Operation Center (SOC) analysts, and distinguished engineers who work with cybersecurity in their day to day lives. They will share their skills which they need to secure its clients security systems.',
                objective: '~ An advanced practical skill-set in assuring network security against all threats including - advanced hackers, trackers, exploit kits, Wi-Fi attacks and much more.\n~ Become a cyber security specialist\n~ Discover security vulnerabilities across an entire network, by using network hacking techniques and vulnerability scanning.\n~ In this volume, we take a detailed look at network security.\n~ The very latest up-to-date information and methods.\n~ You will be able to configure firewalls on all platforms including Windows, MacOS, and Linux for all types of attack scenarios.\n~ We look at search engine privacy - we will best understand how to mitigate the tracking and privacy issues of search engines and their associated services.\n~ What are the best password managers to use and why. How passwords are cracked, and how to mitigate the password attacks.',
                source: 'IT Pro TV',
                popularity: 66.8,
                height: 0.4,
                width: 0.4,
              ),
                        CourseCard(
                          accentcolor: 0xFFf26b0a,
                          buttoncolor: 0xFFff0077,
                          buttontextcolor: 0xffffffff,
                          cardimage: 'https://drive.google.com/uc?export=view&id=1zLTqIYqdsYezmyR_2jX5s25GSLi-ayUH',
                          courseimage: 'https://drive.google.com/uc?export=view&id=1E2O7J1PuzdmTUpIHK_Gg66pg0TW88mok',
                          courselink: 'https://drive.google.com/open?id=1EBcWzDZSNgEkzA2aueNDHtIxE4z9Jn77',
                          objective: '~ In-depth knowledge of Deep Neural Networks\n~ Comprehensive knowledge of various Neural Network architectures such as Convolutional Neural Network, Recurrent Neural Network, Autoencoders\n~ Implementation of Collaborative Filtering with RBM\n~ The exposure to real-life industry-based projects which will be executed using TensorFlow library\n~ Rigorous involvement of an SME throughout the AI & Deep Learning Training to learn industry standards and best practices',
                          overview: 'TensorFlow makes it easy for beginners and experts to create machine learning models for desktop, mobile, web, and cloud. In this courese, you will learn the foundation of TensorFlow. This course is both for beginners and experts to help you create your next machine learning project. After completing of this course you would be able to deploy your own Machine Learning models to Websites, Mobile Applications, and Desktops Softwares.',
                          source: '365 DataScience',
                          title: 'Deep Learning with TensorFlow',
                          popularity: 48.0,
                          height: 0.4,
                          width: 0.4,
                        ),
              CourseCard(
                cardimage: 'https://drive.google.com/uc?export=view&id=1_NZWMbA2NK-ll8v_QNKi426G1K31HUrO',
                courseimage: 'https://drive.google.com/uc?export=view&id=1cjlfM1l5o9XftblG5TKsYjBtPmO_A2tC',
                courselink: 'https://drive.google.com/open?id=0B1HQDi7EkA9XOVpPZFd0RW83bk0',
                buttoncolor: 0xFFFF7EDB,
                buttontextcolor: 0xffF1E6B7,
                accentcolor: 0xff99B5FF,
                title: 'Mordern Designing with CSS',
                overview: 'This course is for both beginners and seasoned developers that want to learn how to build responsive websites and user interfaces with modern HTML5 and CSS3+ technologies like Flexbox and CSS Grid as well as the Sass pre-compiler. This course includes hours of both learning & studying sections along with real life projects. Stop having to rely on frameworks like Bootstrap for your user interface and learn how to create your own layouts and utility classes to build custom responsive websites and app UIs.\n\nThe first few sections are tailored for beginners so even if you have never built anything before, you will learn all of the basics. If you already have experience with basic HTML & CSS, just move to section 3 or 4 and get started.',
                objective: '~ Build Multiple High Quality Website & UI Projects\n~ Flexbox & CSS Grid Projects\n~ Website Hosting & Deployment With FTP & Git\n~ HTML5 Semantic Layout & CSS Fundamentals\n~ CSS Variables, Transitions, Dropdowns, Overlays & More',
                source: 'Udemy',
                popularity: 60.4,
                height: 0.4,
                width: 0.4,
              ),
                        CourseCard(
                            accentcolor: 0xFF36a1ff,
                            buttoncolor: 0xFFffb217,
                            buttontextcolor: 0xff000659,
                            cardimage: 'https://drive.google.com/uc?export=view&id=1YmYopofXtS-4kAnwN0ToBDUbT6G4kaZT',
                            courseimage: 'https://drive.google.com/uc?export=view&id=15c05U5VUvaGmZVOo5k6b_bXewe1Bvg_U',
                            courselink: 'https://drive.google.com/open?id=0B1HQDi7EkA9XdWk2TlNmU2RBYnM',
                            objective: '~ Pass the AWS Certified Developer - Associate 2020 Exam\n~ Become intimately familiar with the AWS platform from a developer perspective.\n~ Become A Cloud Guru\n~ Become confident in creating basic Python and PHP code to manipulate AWS environments\n~ Become Amazon Certified',
                            overview: 'Amazon Web Services - (AWS) Certification is fast becoming the must have certificate for any IT professional working with AWS. This course is designed to help you pass the AWS Certified Developer Associate (CDA) 2020 Exam. Even if you have never logged in to the AWS platform before, by the end of our AWS training videos you will be able to take the CDA exam. No specific programming knowledge is needed (though knowing a language would be advantageous) and no prior AWS experience required. With AWS certification under your belt (and optionally after completing our AWS Certified Solutions Architect course - also available on Udemy), you will be in high demand by many employers and will command a superior salary.',
                            source: 'Udemy',
                            title: 'AWS Developer Associate',
                            height: 0.4,
                            popularity: 58.0,
                            width: 0.4,
                            ),
                        CourseCard(
                          accentcolor: 0xFFff40f2,
                          buttoncolor: 0xFFa14aff,
                          buttontextcolor: 0xffe6cfff,
                          cardimage: 'https://drive.google.com/uc?export=view&id=1RZCaRuSiwAHSeyCwpbNr6wi18bv1arTw',
                          courseimage: 'https://drive.google.com/uc?export=view&id=13E1nR2bsU_tVUCzwroKQlw5llZV199vR',
                          courselink: 'https://drive.google.com/open?id=1E2N2ykcOKY9zMGX-WlNJEkSL-34B_GyM',
                          objective: '~ Learn how to develop, compile, and execute C++ programs as well as syntax, functions, containers, and how to link together multiple files.\n~ Learn to build classes, interfaces, and generic templates to create an object-oriented C++ program. Learn how modern C++ includes many tools for writing clean, reusable code.\n~ Learn to control static and dynamic memory in C++ using the Resource Acquisition Is Initialization pattern, pointers, references, and move semantics\n~ C++ supports running multiple execution paths in parallel. Learn how to launch process and threads in order to execute logic in parallel. Then advance to thread synchronization and communication, to experience the full power of concurrent programming\n~ In your Capstone Project, you will put all of your new C++ skills to use! Utilize the core concepts from this Nanodegree program - object-oriented programming, memory management, and concurrency - to build your own application using C++',
                          overview: ' You will learn about a vide variety of high-level C++ software development techniques. It is highly recommended that students complete both the “Introduction to C++” and “Intermediate C++” courses before attempting this one. However, with a solid understanding of the prerequisites, it is not absolutely necessary to take these courses. Prerequisites include an understanding of pointers, memory allocation, file processing, and general OOP concepts. This course will cover the following concepts: Exceptions, C++ templates, Iterators and advanced Class mechanics, and design patterns.',
                          source: 'Tuts Galaxy',
                          title: 'Ultimate C++',
                          popularity: 85.0,
                          height: 0.4,
                          width: 0.4,
                        ),
                        CourseCard(
                              accentcolor: 0xff000444,
                              buttoncolor: 0xff2672ff,
                              buttontextcolor: 0xfffff833,
                              cardimage: 'https://drive.google.com/uc?export=view&id=1aiOL5UgJS5_QY3jY48JlRUdvTUNjY_Y8',
                              courseimage: 'https://drive.google.com/uc?export=view&id=1xKpmB-i6lBbo5B1A30VdAtfABcFljJIS',
                              courselink: 'https://drive.google.com/open?id=0B1jVKZdy3nxaY3h2bFpQbU1La1k',
                              width: 0.4,
                              height: 0.4,
                              objective: '~ Managing Azure subscriptions and access control\n~ Deploying and organizing Azure resources\n~ Implementing, managing, and securing storage\n~ Building, managing, and executing Virtual Machines\n~ Integrating, securing, and managing identities\n~ Configuration and use case implementation of Virtual Networks\n~ Azure Site Recovery\n~ Implementing multi-factor Authentication',
                              overview: 'Azure Solutions Architect is designed to help you prepare for the Microsoft Azure Architect Technologies Exam – Part of Azure Solutions Architect Badge (Expert-level). You will be able you to implement advanced networking configurations, plan authentication and security of the infrastructure, use PaaS solutions and Storage Services to deploy end-to-end cloud solutions.',
                              popularity: 40,
                              source: 'CBT Nuggets',
                              title: 'Cloud Computing with Azure',
                            ),
              CourseCard(
                cardimage: 'https://drive.google.com/uc?export=view&id=1LVJLJfBXIFlki2WkReKiIJRUuTM7DJFZ',
                courseimage: 'https://drive.google.com/uc?export=view&id=1BZHsdlYnbFbe2TjWMQGuUIhpCsbj64VZ',
                courselink: 'https://drive.google.com/open?id=1esxAlAQ7rlh2eM4wdYfcfyOA--raxQul',
                buttoncolor: 0xFFff1239,
                buttontextcolor: 0xFFfff200,
                accentcolor: 0xFFc933ff,
                title: 'iOS Machine Learning',
                overview: 'In this short course, we\'ll show you how to incorporate Apple\'s Core ML framework into your app. You\'ll also get a quick overview of machine learning fundamentals, and exposure to real-world examples of companies using machine learning technology in their iOS apps.',
                objective: '~ Get a quick overview of fundamental machine learning concepts\n~ Learn the basics of Core ML\n~ Incorporate an image classification model into an app\n~ Understand when you would use a custom model\n~ Convert a custom model for use with Core ML\n~ Enjoy bonus features, like an interview with Meghan Kane, the engineer who inspired this course\n~ Build a challenge app',
                source: 'Udemy',
                popularity: 30.4,
                height: 0.4,
                width: 0.4,
              ),
                        CourseCard(
                              accentcolor: 0xff020061,
                              buttoncolor: 0xff30ffa5,
                              buttontextcolor: 0xff020061,
                              cardimage: 'https://drive.google.com/uc?export=view&id=1JIlDoavso4MhHqFbcQklN0dZcwYR5TjM',
                              courseimage: 'https://drive.google.com/uc?export=view&id=1tBZM3BnFGEmTY7DgslQ_bnmyINj-0yZF',
                              courselink: 'https://drive.google.com/open?id=0ByWO0aO1eI_MWDhYcnIteVc0V00',
                              width: 0.848,
                              height: 0.55,
                              objective: '~ Learn how to create and run a simple Android app\n~ Create simple layouts for Android\n~ Learn about the Android Studio IDE\n~ Connect to the Internet and communicate with web APIs\n~ Learn about the components that convert a list of data into visual UI elements\n~ Learn how to create Intents that apps outside your control can respond to\n~ Learn how to persist data between orientation and other changes\n~ Allow users to customize some aspects of your app\n~ Learn how Content Providers provide an interface to share data\n~ Understand how architecture components can help you build robust and efficient apps\n~ Create notifications and schedule long-running background processes\n~ Try different layouts, views, viewgroups, and methods of databinding\n~ Use design principles to create apps that look great across multiple form factors',
                              overview: 'Take your Android coding skills to the next level in our free, self-paced Advanced Android Development training. The course uses the Java programming language and teaches you ways to expand the user experience, improve app performance, and add features like custom views, animations, and location-awareness.',
                              popularity: 80,
                              source: 'Udemy, Lynda & O\'Reilly',
                              title: 'Complete Android Development',
                            ),
          ],
        ),
      ],
    );
  }
}
